### ISSUE TITLE
Decide on whether we're deprecating `did:key`

### ISSUE THREAD

**Issue by mistermoe** [TBD54566975/web5-spec#13]
> [!WARNING]
> hold off on implementing any additional functionality related to `did:key` until a decision is made

> [!NOTE]
> Hoping to land a decision here by EOD 11/14/2023 US

both `web5-kt` and `web5-js` have `did:key` implementations.  We need to decide whether we want to deprecate `did:key` and when. 

I imagine we'll likely want to wait until we have `did:jwk` implemented in both sdks. 

If we intend to continue maintaining `did:key` we need to produce test vectors.

**Comment by decentralgabe** [comment]
There are did:key test vectors in the spec repo. That said, I believe multibase is unnecessary complexity for us. Microsoft and others are moving towards did:jwk since JWKs are widely adopted and standardized (multiformats couldn't get into IETF).

I recommend we move quickly to implement did:jwk (with test vectors for the key types we support) and deprecate did:key.

**Comment by decentralgabe** [comment]
Yes we are!
