### ISSUE TITLE
Should we use `misc` in JwtClaimsSet to store the vc object? 

### ISSUE THREAD

**Issue by jiyoontbd** [TBD54566975/web5-spec#143]
https://github.com/TBD54566975/web5-kt/pull/262#discussion_r1536091175

putting it here because if move away from `misc` then we have to change implementation for 2+ web5 sdks

**Comment by decentralgabe** [comment]
This is not directly what your issue is about, but I believe it is worth addressing now. If you would like me to move this to a new issue I am happy to.

--------------------------------------

More broadly we should not write our own libraries for widely adopted industry standards when applicable. There are a number of reasons for this:

1. **expertise in specialization**: Creating and maintaining libraries for these specifications requires a level of expertise that is both rare and expensive. These are specialized fields where security and compliance are not just features but the foundation of the software itself. By using established open source libraries, we leverage years of collective expertise that we, frankly, do not possess and should not divert our resources to acquire, as these areas fall outside our core mission.

2. **proven and trusted tools already exist**: The availability of open-source tooling for these standards isn't just about what exists, but what has been battle-tested. Libraries across languages [1] [2] [3], have been scrutinized by security experts worldwide for years. This is not just about popularity but about trust – these tools have been vetted and validated across countless deployments, including environments where security cannot be compromised.

3. **collective wisdom and security**: By choosing to create our own solutions, we isolate ourselves from the ongoing security dialogue happening in the open-source community. The "wisdom of the crowd" in open-source projects leads to more secure, interoperable, and robust software. When vulnerabilities are discovered, the community's response is fast, something an we will have a tough time matching in speed and depth.

4. **efficiency and focus**: I acknowledge it's tempting to reinvent the wheel, and I have done this myself in the past a few times...usually from a desire for control and customization. That said, "not invented here" syndrome is a known pitfall, leading to wasted resources on solving problems that have already been addressed. Our efforts are better directed towards innovation in our core business areas, rather than duplicating work that doesn't offer a competitive advantage.

I will caveat this with saying there may be times where there are good reasons to create our own implementations of things, namely when using an existing open source implementation causes more harm than help and does not accelerate our improve our efforts. I believe such instances should be rare and scrutinized and follow the following practice:

1. Use open source libraries
2. If problems arise, contribute back to open source libraries
3. If contributes take time, fork open source libraries
4. As a last resort, create our own implementations

[1] Popular go JW* implementations [lestratt-go with 1.8k stars, 3.4k+ uses](https://github.com/lestrrat-go/jwx), [go-jose created by Square - 2k stars, hundreds of usages](https://github.com/square/go-jose)
[2] Popular JVM JW* implementations [nimbus](https://connect2id.com/products/nimbus-jose-jwt), [auth0's java-jwt with 5.6k stars, 87.4k+ usages](https://github.com/auth0/java-jwt), 
[3] Popular JS/TS JW* implementations [jose with 8.7M+ downloads](https://www.npmjs.com/package/jose)

**Comment by decentralgabe** [comment]
related #144

**Comment by decentralgabe** [comment]
curious how this might surface in the payloads we create? my understanding was that this should be a construct internal to sdks

**Comment by decentralgabe** [comment]
@jiyoontbd can this be closed?

**Comment by jiyoontbd** [comment]
relevant comment: https://github.com/TBD54566975/web5-spec/issues/145#issuecomment-2302588366
